spring.application.name=inventario-service
server.port=8084

spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


spring.datasource.url=jdbc:oracle:thin:@cafeteria_high?TNS_ADMIN=C:/oracle


spring.datasource.username=INVENTARIO
spring.datasource.password=Petunia123456789

jwt.secret=CLAVE_SUPER_LARGA_ULTRA_SECRETA_DE_MUCHOS_CARACTERES_123456789

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


logging.level.org.hibernate=DEBUG
logging.level.com.zaxxer.hikari=DEBUG


spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.idle-timeout=30000